// Copyright 2026 The porthole Authors
// SPDX-License-Identifier: Apache-2.0

// Package service installs and controls the porthole client daemon as an operating system service: a systemd unit on
// Linux, a launchd job on macOS and a Windows service (SCM) on Windows (ADR 0006). The text of the unit and the plist
// is generated by pure functions that are covered by golden tests on every OS; the commands that change the system
// (systemctl, launchctl, useradd) go through a [Runner] that tests replace.
package service

import (
	"context"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
	"time"
)

// DefaultName is the service name used by `porthole service`: the systemd unit, the Windows service and the suffix
// of the launchd label (io.github.eto-a.porthole).
const DefaultName = "porthole"

// DefaultDisplayName and DefaultDescription are shown by the Windows service manager.
const (
	DefaultDisplayName = "porthole tunnel client"
	DefaultDescription = "porthole tunnel client daemon: keeps tunnels to a portholed server up and serves the local API."
)

// ClientUser is the unprivileged account the Linux system unit runs as; Install creates it when it is missing.
const ClientUser = "porthole-client"

var (
	// ErrNotElevated is returned by the operations that need root or Administrator when the process has neither.
	ErrNotElevated = errors.New("this needs root or Administrator rights; run it from an elevated terminal (it never elevates itself)")
	// ErrNotInstalled is returned by Start, Stop and Restart when the service is not installed.
	ErrNotInstalled = errors.New("the service is not installed")
	// ErrUnsupported is returned where an OS has no such thing: a Windows user service, or any service on another OS.
	ErrUnsupported = errors.New("not supported on this operating system")
)

// Spec describes the service to install.
type Spec struct {
	// Name is the service name; empty means [DefaultName]. Lowercase letters, digits, '.', '_' and '-'.
	Name string
	// DisplayName and Description are used by Windows only; empty means the defaults above.
	DisplayName string
	Description string
	// Exe is the absolute path of the porthole binary. It must already be in its final place.
	Exe string
	// Args are the arguments after Exe, for example "daemon", "--config", "...", "--tunnels", "...". On Linux an empty
	// Args keeps the arguments of the unit in deploy/ (which assume the system paths of the packages).
	Args []string
	// User selects the per-user variant (systemd user unit, LaunchAgent). Windows has none.
	User bool
	// LogDir is where launchd writes stdout and stderr (macOS); empty means the default of the variant.
	LogDir string
}

// State is the state of a service as reported by the service manager.
type State struct {
	Installed bool
	Running   bool
	PID       int
	// Detail is the manager's own wording ("active (running)", "state = running", "STOPPED").
	Detail string
}

// Manager controls one service per call. Install and Uninstall need elevation (the user variant excepted) and return
// [ErrNotElevated] otherwise. An empty name means [DefaultName].
type Manager interface {
	// Install writes (or updates, so it can be re-run) the definition, enables it for the next boot or login and
	// starts it; a service that is already running is restarted to apply the new definition.
	Install(Spec) error
	// Uninstall stops and removes the service. Removing what is not installed is not an error.
	Uninstall(name string) error
	Start(name string) error
	Stop(name string) error
	Restart(name string) error
	// Status returns Installed=false (and no error) for a service that does not exist.
	Status(name string) (State, error)
}

// New returns the manager of this OS: systemd, launchd or the Windows SCM. user selects the per-user variant; it is
// [ErrUnsupported] on Windows and on an OS without any of the three.
func New(user bool) (Manager, error) {
	switch runtime.GOOS {
	case "linux":
		return newSystemd(user)
	case "darwin":
		return newLaunchd(user)
	case "windows":
		return newSCM(user)
	default:
		return nil, fmt.Errorf("services on %s: %w", runtime.GOOS, ErrUnsupported)
	}
}

// Runner runs the commands that change the system. The output is stdout and stderr together.
type Runner interface {
	Run(ctx context.Context, name string, args ...string) ([]byte, error)
}

// commandTimeout bounds one systemctl/launchctl/useradd call.
const commandTimeout = 60 * time.Second

type execRunner struct{}

func (execRunner) Run(ctx context.Context, name string, args ...string) ([]byte, error) {
	ctx, cancel := context.WithTimeout(ctx, commandTimeout)
	defer cancel()
	out, err := exec.CommandContext(ctx, name, args...).CombinedOutput()
	if err != nil {
		return out, fmt.Errorf("%s %s: %w: %s", name, strings.Join(args, " "), err, strings.TrimSpace(string(out)))
	}
	return out, nil
}

var nameRE = regexp.MustCompile(`^[a-z0-9][a-z0-9._-]{0,63}$`)

// checkName validates a service name (empty means the default).
func checkName(name string) (string, error) {
	if name == "" {
		name = DefaultName
	}
	if !nameRE.MatchString(name) {
		return "", fmt.Errorf("service name %q: lowercase letters, digits, '.', '_' and '-' only, at most 64 characters", name)
	}
	return name, nil
}

// normalize fills the defaults and checks the fields that end up in file names and command lines.
func (s Spec) normalize() (Spec, error) {
	name, err := checkName(s.Name)
	if err != nil {
		return s, err
	}
	s.Name = name
	if s.DisplayName == "" {
		s.DisplayName = DefaultDisplayName
	}
	if s.Description == "" {
		s.Description = DefaultDescription
	}
	if s.Exe == "" {
		return s, errors.New("the path of the binary is empty")
	}
	if !isAbs(s.Exe) {
		return s, fmt.Errorf("the path of the binary must be absolute, got %q", s.Exe)
	}
	for _, a := range append([]string{s.Exe}, s.Args...) {
		if strings.ContainsAny(a, "\x00\r\n") {
			return s, fmt.Errorf("argument %q contains a control character", a)
		}
	}
	return s, nil
}

// isAbs accepts Unix and Windows absolute paths on every OS, so the golden tests behave the same everywhere.
func isAbs(p string) bool {
	if strings.HasPrefix(p, "/") || strings.HasPrefix(p, `\\`) {
		return true
	}
	return len(p) >= 3 && p[1] == ':' && (p[2] == '\\' || p[2] == '/') &&
		(p[0] >= 'a' && p[0] <= 'z' || p[0] >= 'A' && p[0] <= 'Z')
}

// writeFileAtomic writes data next to path and renames it over, so a reader never sees half a file.
func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	f, err := os.CreateTemp(filepath.Dir(path), ".porthole-*")
	if err != nil {
		return err
	}
	tmp := f.Name()
	_, err = f.Write(data)
	if cerr := f.Close(); err == nil {
		err = cerr
	}
	if err == nil {
		err = os.Chmod(tmp, perm)
	}
	if err == nil {
		err = os.Rename(tmp, path)
	}
	if err != nil {
		_ = os.Remove(tmp)
		return err
	}
	return nil
}
